In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [13]:
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

# Multiply
x2 = tf.add(x2, 3)
result = tf.multiply(x1, x2)

# Initialize Session and run `result`
with tf.Session() as sess:
    call_f(result)

[ 8 18 30 44]


In [21]:
def call_f(sess,result):
  
    output = sess.run(result)
    return output

In [24]:
x = tf.constant([[37.0, -23.0], [1.0, 4.0]])
w = tf.Variable(tf.random_uniform([2, 2]))
y = tf.matmul(x, w)
output = tf.nn.softmax(y)
init_op = w.initializer

with tf.Session() as sess:
  # Run the initializer on `w`.
    sess.run(init_op)

  # Evaluate `output`. `sess.run(output)` will return a NumPy array containing
  # the result of the computation.
    print(sess.run(output))

  # Evaluate `y` and `output`. Note that `y` will only be computed once, and its
  # result used both to return `y_val` and as an input to the `tf.nn.softmax()`
  # op. Both `y_val` and `output_val` will be NumPy arrays.
    y_val, y_val2, output_val = sess.run([y,y, output])

[[0.99741    0.00259006]
 [0.18851532 0.8114847 ]]


In [18]:
output_val

array([[9.9984658e-01, 1.5335709e-04],
       [3.5695216e-01, 6.4304787e-01]], dtype=float32)